# Generated by Django 4.0.1 on 2022-01-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlddata', '0013_alter_worldhappiness_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaterquality',
            name='city',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='worlddata.worldcities'),
        ),
        migrations.AlterField(
            model_name='countryreligion',
            name='iso3',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='worlddata.iso'),
        ),
        migrations.AlterField(
            model_name='internetprices',
            name='city',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='worlddata.worldcities'),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='country_iso',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='worlddata.worldcities'),
        ),
    ]
