# Generated by Django 4.0.1 on 2022-01-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldHappiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('life_ladder', models.FloatField(blank=True, default=None, null=True)),
                ('log_GDP_per_capita', models.FloatField(blank=True, default=None, null=True)),
                ('social_support', models.FloatField(blank=True, default=None, null=True)),
                ('healthy_life_expectancy', models.FloatField(blank=True, default=None, null=True)),
                ('freedom_of_life_choices', models.FloatField(blank=True, default=None, null=True)),
                ('generosity', models.FloatField(blank=True, default=None, null=True)),
                ('perceptions_of_corruption', models.FloatField(blank=True, default=None, null=True)),
                ('positive_affect', models.FloatField(blank=True, default=None, null=True)),
                ('negative_affect', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
