# Generated by Django 4.0.1 on 2022-01-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('city_ascii', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('iso2', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('iso3', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('admin_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('capital', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('population', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
