# Generated by Django 4.0.1 on 2022-01-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0002_worldcities'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('price_usd', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
