# Generated by Django 4.0.1 on 2022-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0003_internetprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('main_religion', models.CharField(max_length=200)),
            ],
        ),
    ]
