# Generated by Django 4.0.1 on 2022-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0004_countryreligion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirWaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=200)),
                ('air_quality', models.FloatField()),
                ('water_quality', models.FloatField()),
            ],
        ),
    ]
