# Generated by Django 4.0.1 on 2022-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0006_iso_alter_airwaterquality_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='numeric',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
