# Generated by Django 4.0.1 on 2022-01-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0008_iso_iso2_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcities',
            name='country',
        ),
        migrations.RemoveField(
            model_name='worldcities',
            name='iso2',
        ),
    ]
