# Generated by Django 4.0.1 on 2022-01-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0009_remove_worldcities_country_remove_worldcities_iso2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaterquality',
            name='air_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airwaterquality',
            name='water_quality',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
