# Generated by Django 4.0.1 on 2022-01-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0011_worldhappiness_country_iso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldhappiness',
            name='country_name',
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='country_iso',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
    ]
