# Generated by Django 4.0.1 on 2022-01-20 15:27

from django.db import migrations, models
import world_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0013_alter_worldhappiness_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryreligion',
            name='iso3',
            field=models.CharField(max_length=3, verbose_name=world_data.models.Iso),
        ),
    ]
