# Generated by Django 4.0.1 on 2022-01-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0015_alter_countryreligion_iso3_alter_iso_iso3'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcities',
            name='iso3_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world_data.iso'),
        ),
    ]
