# Generated by Django 4.0.1 on 2022-01-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_data', '0016_worldcities_iso3_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldhappiness',
            name='iso3_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world_data.iso'),
        ),
        migrations.AlterField(
            model_name='worldcities',
            name='iso3',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='worldcities',
            name='iso3_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_data.iso'),
        ),
    ]
