# Generated by Django 4.0.1 on 2022-01-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldhappiness',
            name='freedom_of_life_choices',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='generosity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='healthy_life_expectancy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='life_ladder',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='log_GDP_per_capita',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='negative_affect',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='perceptions_of_corruption',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='positive_affect',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='social_support',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldhappiness',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
